- packages/svelte-materialify/@types/components/AppBar.d.ts
- packages/svelte-materialify/@types/components/Button.d.ts
- packages/svelte-materialify/@types/components/Icon.d.ts
- packages/svelte-materialify/@types/components/Input.d.ts
- packages/svelte-materialify/@types/components/MaterialApp.d.ts
- packages/svelte-materialify/@types/components/NavigationDrawer.d.ts
- packages/svelte-materialify/@types/components/Overlay.d.ts
- packages/svelte-materialify/@types/components/TextField.d.ts
- packages/svelte-materialify/@types/components/card/card.d.ts
- packages/svelte-materialify/@types/components/list/List.d.ts
- packages/svelte-materialify/@types/components/list/ListGroup.d.ts
- packages/svelte-materialify/@types/components/list/ListItem.d.ts
- packages/svelte-materialify/@types/components/list/ListItemGroup.d.ts
- packages/svelte-materialify/@types/index.d.ts
- packages/svelte-materialify/@types/shared.d.ts
The types I added to my project, if that can help you or somebody else :-)
Might be wrong on a few points (I don't use all of them so: to be reviewed).
> feat(typing): adds more typescript definitions

- packages/svelte-materialify/src/components/TextField/_variables.scss
> Fix TextField wrapper padding for resize-grabber

- packages/svelte-materialify/src/components/Tooltip/Tooltip.svelte
I used [offsetLeft](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetLeft) and [offsetTop](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetTop) to get the position but they are relative the parent. I changed to [getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) + scroll to be relative to the viewport.
> Fix Tooltip position when inside relative element

- packages/svelte-materialify/src/components/Textarea/Textarea.svelte
Textareas don't respect the `rows` property when `autogrow` is set to true, as their height is set to `0` when the input changes. This bug doesn't occur when changing `0` to `'auto'`.
> textareas don't respect rows property when autogrow is set to true

- packages/svelte-materialify/src/components/Checkbox/Checkbox.svelte
[group update feature](https://svelte-materialify.vercel.app/components/checkboxes/#groups) is not updating the group variable when checkbox value is zero:
`value` when set to `0` was evaluating to `false` inside the if statements on line 43 and 48. I believe the intended check is to see if the value is valid. I changed it to `value != null` and I got the same behavior as with the native checkbox components
```svelte
<div class="ma-5">
{#each [0,1,2,3] as i}
<Checkbox color="secondary" bind:group={selected} value={i}>value={i}</Checkbox>
{/each}
<div>
Selected: {JSON.stringify(selected)}
</div>
</div>
```
Output before the fix:
Output after the fix:
> fix(checkbox): update groupUpdate method edge case when value = 0

- packages/svelte-materialify/src/styles/generic/_reset.scss
A little fix to keep the pointer cursor when `aria-disabled` is `false`. To reproduce pass `false` to the `disabled` prop of a `Button`.
> fix(styles): update aria-disabled selector

- packages/svelte-materialify/@types/index.d.ts
Thank you for such a great UI framework :tada:
You have `Menu.d.ts`, but it is not exported in `index.d.ts`.
I just added one line to `index.d.ts`.
> fix(types): missing export of Menu

- packages/docs/src/playground/Breadcrumbs.svelte
Fixes the divider dropdown [here](https://svelte-materialify.vercel.app/components/breadcrumbs/#playground).
Preview: https://svelte-materia-git-fork-dincahill-fix-breadcrumbs-pla-097a96.thecomputerm.vercel.app/components/breadcrumbs/#playground.
> docs(Breadcrumbs): use slot for divider in playground

- packages/svelte-materialify/src/actions/ClickOutside/index.js
Actually elements causing events with stopPropagation don't trigger function that detect click outside, because event propagation is bubbling by default and it stops at event target. 
By setting capture to true, event propagation will start from window and the function will be triggered correctly.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture
> fix(clickOutside): set event propagation to capturing phase

- packages/docs/static/styles.css
- packages/svelte-materialify/src/components/MaterialApp/MaterialApp.scss
- packages/svelte-materialify/src/components/MaterialApp/MaterialApp.svelte
Needs min-height to work for both: sites which don't cover the whole screen and sites with scroll.
(btw. there seems to be inconsistent browser behavior based on html/body height, please test more browsers)
chrome88 works
> feat(MaterialApp): make full height

- packages/api-generator/src/TextField.json
- packages/svelte-materialify/src/components/TextField/TextField.svelte
https://github.com/TheComputerM/svelte-materialify/issues/121
> refactor: remove deprecated event keypress from TextField

- packages/docs/src/examples/Card/customActions.svelte
If using {#if} with child container that has padding, the padding/margin makes the transition jagged (padding instantly appears before transition can finish)
To correct this, {#if} should have a child container that does the transition. The grandchildren can have whatever padding/margin needed.
tl;dr
```
{#if}
<div transition>
<div paddings here>
{content}
</div>
</div
{/if}
```
Edit:
Closes #127
> Update customActions.svelte Transition Container Update

- packages/svelte-materialify/src/components/Select/Select.svelte
This PR enables on:change event support for the Select component. Not quite sure what needs to be done to update the documentation (if at all?). This PR should replace #133.
Closes #131, Closes #133
> fix(Select): on:change support for select component

- packages/svelte-materialify/src/components/ItemGroup/ItemGroup.svelte
Hi, I've tried to fix #90 and have something that seems to work. Hopefully someone can use this to fix it properly.
This fixes multiple broken playgrounds and examples in the docs.
`value = [val]` fixes dropdowns [like](https://svelte-materialify.vercel.app/components/alerts/#playground) [these](https://svelte-materialify.vercel.app/components/buttons/#playground). Then I had to add `typeof (val) === 'number'` to stop [the first three of these ListItemGroups](https://svelte-materialify.vercel.app/components/list-item-groups/) from breaking.
Preview: https://svelte-materialify-git-fork-dincahill-fix-itemgroup.thecomputerm.vercel.app/components/alerts/#playground
Preview: https://svelte-materialify-git-fork-dincahill-fix-itemgroup.thecomputerm.vercel.app/components/list-item-groups/
> fix(ItemGroup): make value an array if it's not an index

- packages/svelte-materialify/src/components/Tabs/Tab.svelte
It would be very convenient (for my application at least) to be able to react on click events on Tabs, so I forwarded the event. While digging a bit in the API documentation(s), I had the feeling there is some inconsistency between the components regarding the available events. The ListItem component, for example, is forwarding the click event. It would be good IMHO to align these across the components as far as possible.
> feat(Tab): forward click event

- packages/svelte-materialify/src/components/Slider/Slider.svelte
One potential problem remains the displayed value in the thumb. If too many decimal places are defined, the displayed value is exceeding the thumb "area". This is, however, already an issue with very large numbers (>=10000). Possible fixes: 
- Make the size of the thumb customizable
- Make the size of the thumb responsive to the value (no clue how that could be done easily)
- Prevent using the thumb when precision > 1 (not a very reliable workaround)
Should resolve #112
> feat(Slider): add precision prop to customize decimal places of slider value

- packages/svelte-materialify/src/index.d.ts
Resolves #173
Previously, when using the 'Advanced Installation' method outlined
in docs, types would be unavailable. By providing an index.d.ts
file in /src, types become available whether importing from the
compiled package or importing from the package source.
> feat(types): Enable types when importing from /src

- packages/svelte-materialify/@types/Select.d.ts
When `multiple` prop is false, the value of a `<Select />` is a single value, not an array. Updated select.d.ts to reflect this.
> fix(types/select.d.ts): Value can be single value or array

- packages/svelte-materialify/src/components/Slider/Slider.svelte
Closes #171
Based on these two resources, works in my Vite SPA application :
- https://github.com/TheComputerM/svelte-materialify/issues/171#issuecomment-802991037
- https://kit.svelte.dev/docs#troubleshooting-server-side-rendering
> fix: sliderUi library imported incorrectly for SPA and SSR #171

- README.md
the link was empty. put the appropriate meaning, maybe I'm wrong.
> Fix link for "Code of Conduct"

- README.md
the link was empty. put the appropriate meaning, maybe I'm wrong.
> fix link to changelog

- packages/svelte-materialify/@types/index.d.ts
As seen in https://github.com/TheComputerM/svelte-materialify/issues/91#issuecomment-817824818 , the `MaterialAppMin` component is not shown to imports and yields an error in typescript codebases (or checked js codebases).
This should in theory fix it (didn't test it locally).
cc @Florian-Schoenherr
> fix(Types): Add MaterialAppMin type to declaration files

- packages/svelte-materialify/@types/Col.d.ts
- packages/svelte-materialify/@types/Container.d.ts
- packages/svelte-materialify/@types/Divider.d.ts
- packages/svelte-materialify/@types/Row.d.ts
- packages/svelte-materialify/@types/Snackbar.d.ts
Only these five definition files imported SvelteComponent via 'svelte-materialify/@types/shared', while all other definitions used the './shared' relative path. This is a chore commit that brings consistency to the imports.
> feat(definitions): Use relative imports consistently in d.ts files

- packages/svelte-materialify/@types/Breadcrumbs.d.ts
- packages/svelte-materialify/@types/ExpansionPanel.d.ts
- packages/svelte-materialify/@types/Select.d.ts
- packages/svelte-materialify/@types/VirtualList.d.ts
I didnt add the VirtualList export in index.d.ts since it's supposed to be unavailable for now.
If I forgot any slot types, let me know !
> fix(types) Select, Breadcrumbs, ExpansionPanel slot type and VirtualList type

- packages/docs/src/components/doc/Layout.svelte
- packages/docs/src/components/navigation/LeftNavigationDrawer.svelte
- packages/docs/src/components/navigation/RightNavigationDrawer.svelte
- packages/docs/src/routes/index.svelte
- packages/docs/src/util/stores.js
Closes #115. I built my own little scrollspy, only the back-button is not the same, it actually ignores the hash-values. I think that's good, because it means the hash can be set on scroll. For the end of the lifetime of this lib, it should be enough.
> chore: remove gumshoe

- packages/svelte-materialify/src/styles/generic/_display.scss
- packages/svelte-materialify/src/styles/generic/_spacing.scss
- packages/svelte-materialify/src/styles/generic/_typography.scss
- yarn.lock
right now the order of generation in the _spacing.scss file generates all 0,1,2,3...etc classes.
By changing the iteration order, pa-* and ma-* are generated first, so they can be overridden by following classes and be able to achive a  pt-4 pl-4 pr-4 pt-8 by simply writing pa-4 pt-8
> css overrides - makes the pa-* and ma-* overridable.

- packages/svelte-materialify/src/components/List/ListGroup.svelte
Closes #75 
To get a gist of the issue at hand, if you go at https://svelte-materialify.vercel.app/components/lists/#nested and toggle on the nested ListGroup element, everything looks fine. However, if you now double click the `Actions` element (basically closing and opening the nested ListGroup element), you will see that the offset is not applied anymore.
I believe this is due to a weird interaction with Svelte where the transition is applied the the `use:Style` directive doesn't get applied when the element isn't fully removed yet (due to the transition). I tested it locally and couldn't find a proper fix.
However, since the use directive of the `Style` function is updateable, if you reactively update the `offset` variable, the use directive gets reapplied every time you toggle the …
> fix(ListGroup): offset not applied when toggling off and on quickly
