packages/svelte-materialify/src/components/TextField/TextField.svelte
Makes the text input component forward the DOM change event
=> feat(text-input): trigger change event from textfield

packages/svelte-materialify/src/components/Select/Select.svelte
Gives devs the ability to define how the chosen value is shown (inside the underlying TextField).
Closes: #19
=> feat(Select): added `format` prop

lerna.json, packages/svelte-materialify/src/components/Tooltip/Tooltip.svelte
An important fix because the Tooltip is broken. This was a mistake I made after an eslint fix.
=> Fix Tooltip

packages/docs/src/components/doc/Alert.svelte, packages/docs/src/routes/_layout.svelte
2 little bugs that I noticed when I developed the new Tooltip component 😄
=> Docs fixes

packages/docs/src/routes/getting-started/contributing.md
thanks for your prompt response yesterday.
I copied what you told me in the issue and added some more. 
If I managed to to make it work, everyone should be able to.
This is my first public repository pull requests, quite an experience.
=> docs: improve contributing.md documentation

packages/svelte-materialify/src/components/Select/Select.scss
Cursor closes #52.
`max-width` is in accordance with TextField.
=> fix(Select): cursor and width

packages/svelte-materialify/src/styles/generic/_flex.scss
The implementation of flex-grow & flex-shrink as described in the documentation were missing.
=> feat(style): implemented flex grow and shrink

packages/docs/src/playground/Button.svelte
https://user-images.githubusercontent.com/16399020/105905321-432a4200-605d-11eb-9912-560dca9afbaf.mp4
=> Fix error on button size example

packages/docs/src/routes/api/[slug].svelte
=> docs(api): improve separators in slot props list

packages/svelte-materialify/src/components/Select/Select.svelte
I need this for some added functionality inside the Select Menu. If I can keep it open another way, tell me.
Menu dispatches close, is that forwarded?
=> feat(Select): export closeOnClick

packages/svelte-materialify/src/components/TextField/TextField.svelte
=> feat(TextField): allow manual validation

packages/api-generator/helpers/generate.js, packages/api-generator/src/NavigationDrawer.json, packages/api-generator/src/Select.json, packages/svelte-materialify/@types/NavigationDrawer.d.ts, packages/svelte-materialify/src/components/AppBar/AppBar.scss, packages/svelte-materialify/src/components/NavigationDrawer/NavigationDrawer.scss, packages/svelte-materialify/src/components/NavigationDrawer/NavigationDrawer.svelte
=> fix: set Appbar z-index

packages/api-generator/src/Alert.json, packages/api-generator/src/Badge.json, packages/api-generator/src/Dialog.json, packages/api-generator/src/ExpansionPanel.json, packages/api-generator/src/ListGroup.json, packages/api-generator/src/NavigationDrawer.json, packages/api-generator/src/Snackbar.json, packages/svelte-materialify/src/components/Alert/Alert.svelte, packages/svelte-materialify/src/components/Badge/Badge.svelte, packages/svelte-materialify/src/components/Dialog/Dialog.svelte, packages/svelte-materialify/src/components/ExpansionPanels/ExpansionPanel.svelte, packages/svelte-materialify/src/components/List/ListGroup.svelte, packages/svelte-materialify/src/components/NavigationDrawer/NavigationDrawer.svelte, packages/svelte-materialify/src/components/Snackbar/Snackbar.svelte
=> Forward transition events

packages/docs/src/examples/Grid/_wrapper.svelte, packages/docs/src/routes/actions/intersect.md, packages/docs/src/routes/components/autocomplete.md, packages/docs/src/routes/components/carousels.md, packages/docs/src/routes/components/grid.md, packages/docs/src/routes/components/lazy.md, packages/docs/src/routes/components/material-app.md, packages/docs/src/routes/components/virtual-lists.md, packages/svelte-materialify/src/components/Slider/Slider.svelte
small fixes:
- MaterialApp now has description+keywords
- Grid docs don't bleed out
- Slider hint prop removed
Closes #108
=> Add some stub messages instead of 404 + small fixes

packages/svelte-materialify/src/components/ItemGroup/ItemGroup.svelte
=> fix(ItemGroup): cross mandatory and multiple

packages/svelte-materialify/@types/Subheader.d.ts, packages/svelte-materialify/@types/index.d.ts
Adds missing type definition for subheader component
=> feat(typing): subheader

packages/docs/src/playground/Alert.svelte, packages/docs/src/playground/AppBar.svelte, packages/docs/src/playground/Avatar.svelte, packages/docs/src/playground/Breadcrumbs.svelte, packages/docs/src/playground/Chip.svelte, packages/docs/src/playground/Icon.svelte, packages/docs/src/playground/NavigationDrawer.svelte, packages/svelte-materialify/src/components/Icon/Icon.svelte, packages/svelte-materialify/src/components/ItemGroup/ItemGroup.svelte
reverts #94 and fixes it for real.
=> fix: select issue

packages/svelte-materialify/@types/ItemGroup.d.ts
=> Fixed ItemGroup typings to allow for non-array value prop

packages/svelte-materialify/src/components/Select/Select.svelte
it is enough to set a simple check condition that in fact does not change anything, but forces the component to update the data.
=> force update the items when they are changed

packages/svelte-materialify/@types/Footer.d.ts, packages/svelte-materialify/@types/index.d.ts
Added type for the Footer component.
=> fix(types) added Footer type

packages/svelte-materialify/src/components/Tooltip/Tooltip.svelte
=> fix:  tooltip stucked #140

packages/svelte-materialify/@types/Chip.d.ts
Exposes `Chip` on imports for typescript.
=> feat(Chip.d.ts): New definition file

packages/svelte-materialify/@types/index.d.ts
Added the Chip.d.ts definition file in the previous pull request, but forgot to add it to index.d.ts.
=> fix(index.d.ts): added Chip export

packages/svelte-materialify/src/components/Textarea/Textarea.svelte
This also makes the Textarea more in line with the TextField component
I also fixed autogrow not being updated if value is dynamically updated to a big value, see comments
REPL that shows issue(s) : https://svelte.dev/repl/1154fe4b3434494b88c2e1cf35960c76?version=3.38.1
Closes #247
=> fix(Textarea): Fix label not being reactive (#247)
